spring.datasource.url=jdbc:postgresql://localhost:5432/vivarota_db
spring.datasource.username=postgres
spring.datasource.password=123Admin
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect




api.security.token.secret=${JWT_SECRET:minha_chave_secreta_super_segura_123456}


spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

springdoc.swagger-ui.path=/swagger-ui.html

mapbox.token=pk.eyJ1IjoibGVvd29yazIwIiwiYSI6ImNtb2RtdmZ5eDA0Zjgyd29rdm15Z3V0bGkifQ.EXpJbB1TkTN2zHkxuDaM9Q